import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' }
];

export const TRANSLATIONS = {
  en: {
    brandName: 'SmartSweep',
    citizenPortal: 'Citizen Portal',
    crewPortal: 'Field Crew Portal',
    adminPortal: 'Admin Command Portal',
    home: 'Home',
    citizenHub: 'Citizen Hub',
    crewDashboard: 'Crew Dashboard',
    commandCenter: 'Command Center',
    reportIssue: 'Report Issue',
    myComplaints: 'My Complaints',
    bulkPickup: 'Bulk Pickup',
    schedule: 'Timetable',
    publicFeed: 'Public Feed',
    assignedTasks: 'Assigned Tasks',
    bulkDispatches: 'Bulk Dispatches',
    fleetVehicles: 'Fleet & Trucks',
    toolsPPE: 'Tools & PPE',
    reportsTrends: 'Reports & Trends',
    workforce: 'Workforce',
    fleetDispatch: 'Fleet Dispatch',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome to SmartSweep',
    totalCaseload: 'Total Caseload',
    pending: 'Pending',
    inProgress: 'In Progress',
    resolved: 'Resolved',
    cancelled: 'Cancelled',
    enRoute: 'En Route',
    slaCompliance: 'SLA Compliance',
    activeDispatches: 'Active Dispatches',
    hazard: 'Hazard',
    location: 'Location',
    ward: 'Ward',
    actions: 'Actions',
    switchPortal: 'Switch Portal',
    themeMode: 'Theme Mode',
    darkForest: 'Dark Forest',
    crispLight: 'Crisp Light',
    selectLanguage: 'Select Language',
    fileWasteReport: 'File a Waste Report',
    bookBulkPickup: 'Book Bulk Pickup',
    viewTimetable: 'View Timetable',
    viewFeed: 'View Live Stream',
    todayCollection: "Today's Waste Collection",
    morningSlot: 'Morning Collection',
    eveningSlot: 'Evening Sweep',
    attachPhoto: 'Attach Spot Photo',
    submitReport: 'Submit Waste Report',
    detectGPS: 'Auto-detect GPS',
    rateResolution: 'Rate Resolution',
    applaud: 'Applaud',
    applauded: 'Applauded!',
    discussion: 'Discussion',
    wasteRemoved: 'Waste Cleared',
    safetyScore: 'Safety Score',
    shift: 'Shift'
  },
  hi: {
    brandName: 'स्मार्टस्वीप (SmartSweep)',
    citizenPortal: 'नागरिक पोर्टल',
    crewPortal: 'सफाई कर्मी पोर्टल',
    adminPortal: 'प्रशासक कमान पोर्टल',
    home: 'होम',
    citizenHub: 'नागरिक हब',
    crewDashboard: 'कर्मी डैशबोर्ड',
    commandCenter: 'कंट्रोल सेंटर',
    reportIssue: 'शिकायत दर्ज करें',
    myComplaints: 'मेरी शिकायतें',
    bulkPickup: 'बड़ा कचरा पिकअप',
    schedule: 'समय सारणी',
    publicFeed: 'पब्लिक फीड',
    assignedTasks: 'आवंटित कार्य',
    bulkDispatches: 'थोक कचरा वाहन',
    fleetVehicles: 'सफाई वाहन और ट्रक',
    toolsPPE: 'सुरक्षा उपकरण और PPE',
    reportsTrends: 'रिपोर्ट्स और आंकड़े',
    workforce: 'कार्यबल',
    fleetDispatch: 'वाहन प्रेषण',
    signIn: 'लॉग इन करें',
    signOut: 'लॉग आउट',
    createAccount: 'नया खाता बनाएं',
    welcomeBack: 'स्मार्टस्वीप में आपका स्वागत है',
    totalCaseload: 'कुल मामले',
    pending: 'लंबित',
    inProgress: 'प्रगति पर',
    resolved: 'समाधान हो चुका',
    cancelled: 'रद्द',
    enRoute: 'रास्ते में',
    slaCompliance: 'SLA अनुपालन दर',
    activeDispatches: 'सक्रिय वाहन',
    hazard: 'खतरा स्तर',
    location: 'स्थान / पता',
    ward: 'वार्ड',
    actions: 'कार्रवाई',
    switchPortal: 'पोर्टल बदलें',
    themeMode: 'थीम मोड',
    darkForest: 'डार्क फॉरेस्ट',
    crispLight: 'क्रिसप लाइट',
    selectLanguage: 'भाषा चुनें',
    fileWasteReport: 'कचरे की शिकायत दर्ज करें',
    bookBulkPickup: 'बड़ा कचरा पिकअप बुक करें',
    viewTimetable: 'समय सारणी देखें',
    viewFeed: 'लाइव स्ट्रीम देखें',
    todayCollection: 'आज का कचरा संग्रह समय',
    morningSlot: 'सुबह का संग्रह',
    eveningSlot: 'शाम की सफाई',
    attachPhoto: 'फोटो संलग्न करें',
    submitReport: 'रिपोर्ट सबमिट करें',
    detectGPS: 'GPS से पता लगाएं',
    rateResolution: 'सफाई की रेटिंग दें',
    applaud: 'सराहना करें',
    applauded: 'सराहना की गई!',
    discussion: 'चर्चा',
    wasteRemoved: 'कचरा हटाया गया',
    safetyScore: 'सुरक्षा स्कोर',
    shift: 'ड्यूटी शिफ्ट'
  },
  kn: {
    brandName: 'ಸ್ಮಾರ್ಟ್‌ಸ್ವೀಪ್',
    citizenPortal: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    crewPortal: 'ಸ್ವಚ್ಛತಾ ಸಿಬ್ಬಂದಿ ಪೋರ್ಟಲ್',
    adminPortal: 'ಆಡಳಿತ ಆಜ್ಞಾ ಪೋರ್ಟಲ್',
    home: 'ಮುಖಪುಟ',
    citizenHub: 'ನಾಗರಿಕ ಕೇಂದ್ರ',
    crewDashboard: 'ಸಿಬ್ಬಂದಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    commandCenter: 'ಆಡಳಿತ ಕಂಟ್ರೋಲ್ ಸೆಂಟರ್',
    reportIssue: 'ಕಸದ ದೂರು ದಾಖಲಿಸಿ',
    myComplaints: 'ನನ್ನ ದೂರುಗಳು',
    bulkPickup: 'ಭಾರೀ ತ್ಯಾಜ್ಯ ಸಂಗ್ರಹ',
    schedule: 'ವೇಳಾಪಟ್ಟಿ',
    publicFeed: 'ಸಾರ್ವಜನಿಕ ಫೀಡ್',
    assignedTasks: 'ನಿಯೋಜಿತ ಕಾರ್ಯಗಳು',
    bulkDispatches: 'ಭಾರೀ ವಾಹನ ರವಾನೆ',
    fleetVehicles: 'ವಾಹನ ಫ್ಲೀಟ್',
    toolsPPE: 'ಸುರಕ್ಷತಾ ಸಾಧನಗಳು',
    reportsTrends: 'ವರದಿಗಳು ಮತ್ತು ಅಂಕಿಅಂಶ',
    workforce: 'ಸಿಬ್ಬಂದಿ ವರ್ಗ',
    fleetDispatch: 'ವಾಹನ ನಿಯೋಜನೆ',
    signIn: 'ಲಾಗಿನ್ ಮಾಡಿ',
    signOut: 'ಲಾಗ್ ಔಟ್',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    welcomeBack: 'ಸ್ಮಾರ್ಟ್‌ಸ್ವೀಪ್‌ಗೆ ಸುಸ್ವಾಗತ',
    totalCaseload: 'ಒಟ್ಟು ಪ್ರಕರಣಗಳು',
    pending: 'ಬಾಕಿ ಇದೆ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    resolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    cancelled: 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    enRoute: 'ದಾರಿಯಲ್ಲಿದೆ',
    slaCompliance: 'SLA ಅನುಸರಣೆ',
    activeDispatches: 'ಸಕ್ರಿಯ ವಾಹನಗಳು',
    hazard: 'ಅಪಾಯ ಮಟ್ಟ',
    location: 'ಸ್ಥಳ',
    ward: 'ವಾರ್ಡ್',
    actions: 'ಕ್ರಿಯೆಗಳು',
    switchPortal: 'ಪೋರ್ಟಲ್ ಬದಲಾಯಿಸಿ',
    themeMode: 'ಥೀಮ್ ಮೋಡ್',
    darkForest: 'ಡಾರ್ಕ್ ಫಾರೆಸ್ಟ್',
    crispLight: 'ಲೈಟ್ ಮೋಡ್',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    fileWasteReport: 'ಹೊಸ ದೂರು ದಾಖಲಿಸಿ',
    bookBulkPickup: 'ಭಾರೀ ಕಸ ಸಂಗ್ರಹ ಬುಕ್ ಮಾಡಿ',
    viewTimetable: 'ವೇಳಾಪಟ್ಟಿ ವೀಕ್ಷಿಸಿ',
    viewFeed: 'ಲೈವ್ ಫೀಡ್ ವೀಕ್ಷಿಸಿ',
    todayCollection: 'ಇಂದಿನ ಕಸ ಸಂಗ್ರಹ ಸಮಯ',
    morningSlot: 'ಬೆಳಗಿನ ಸಂಗ್ರಹ',
    eveningSlot: 'ಸಂಜೆಯ ಸ್ವಚ್ಛತೆ',
    attachPhoto: 'ಫೋಟೋ ಲಗತ್ತಿಸಿ',
    submitReport: 'ವರದಿ ಸಲ್ಲಿಸಿ',
    detectGPS: 'GPS ಮೂಲಕ ಪತ್ತೆಹಚ್ಚಿ',
    rateResolution: 'ರೇಟಿಂಗ್ ನೀಡಿ',
    applaud: 'ಮೆಚ್ಚುಗೆ ವ್ಯಕ್ತಪಡಿಸಿ',
    applauded: 'ಮೆಚ್ಚಲಾಗಿದೆ!',
    discussion: 'ಚರ್ಚೆ',
    wasteRemoved: 'ತೆರವುಗೊಳಿಸಿದ ಕಸ',
    safetyScore: 'ಸುರಕ್ಷತಾ ಅಂಕ',
    shift: 'ಶಿಫ್ಟ್'
  },
  ta: {
    brandName: 'ஸ்மார்ட்ஸ்வீப்',
    citizenPortal: 'குடிமக்கள் தளம்',
    crewPortal: 'துப்புரவு பணியாளர் தளம்',
    adminPortal: 'நிர்வாக கட்டுப்பாட்டு தளம்',
    home: 'முகப்பு',
    citizenHub: 'குடிமக்கள் மையம்',
    crewDashboard: 'பணியாளர் பலகை',
    commandCenter: 'கட்டளை மையம்',
    reportIssue: 'புகார் பதிவு செய்க',
    myComplaints: 'எனது புகார்கள்',
    bulkPickup: 'பெரிய கழிவு சேகரிப்பு',
    schedule: 'அட்டவணை',
    publicFeed: 'பொது ஓடை',
    assignedTasks: 'ஒதுக்கப்பட்ட பணிகள்',
    bulkDispatches: 'கழிவு வாகனங்கள்',
    fleetVehicles: 'வாகனங்கள்',
    toolsPPE: 'பாதுகாப்பு கருவிகள்',
    reportsTrends: 'அறிக்கைகள்',
    workforce: 'பணியாளர்கள்',
    fleetDispatch: 'வாகன அனுப்புதல்',
    signIn: 'உள்நுழைக',
    signOut: 'வெளியேறுக',
    createAccount: 'கணக்கு உருவாக்குக',
    welcomeBack: 'ஸ்மார்ட்ஸ்வீப்பிற்கு நல்வரவு',
    totalCaseload: 'மொத்த வழக்குகள்',
    pending: 'நிலுவையில்',
    inProgress: 'நடைபெறுகிறது',
    resolved: 'தீர்க்கப்பட்டது',
    cancelled: 'ரத்துசெய்யப்பட்டது',
    enRoute: 'வழியில் உள்ளது',
    slaCompliance: 'SLA இணக்கம்',
    activeDispatches: 'செயலில் உள்ள வாகனங்கள்',
    hazard: 'ஆபத்து நிலை',
    location: 'இடம்',
    ward: 'வார்டு',
    actions: 'செயல்கள்',
    switchPortal: 'தளத்தை மாற்றுக',
    themeMode: 'வண்ண முறை',
    darkForest: 'டார்க் முறை',
    crispLight: 'லைட் முறை',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    fileWasteReport: 'கழிவு புகார் அளிக்கவும்',
    bookBulkPickup: 'கழிவு சேகரிப்பை முன்பதிவு செய்க',
    viewTimetable: 'அட்டவணையை காண்க',
    viewFeed: 'நேரலை காண்க',
    todayCollection: 'இன்றைய கழிவு சேகரிப்பு',
    morningSlot: 'காலை சேகரிப்பு',
    eveningSlot: 'மாலை தூய்மை',
    attachPhoto: 'புகைப்படம் இணைக்கவும்',
    submitReport: 'சமர்ப்பிக்கவும்',
    detectGPS: 'GPS கண்டறிதல்',
    rateResolution: 'மதிப்பீடு செய்க',
    applaud: 'பாராட்டு',
    applauded: 'பாராட்டப்பட்டது!',
    discussion: 'விவாதம்',
    wasteRemoved: 'அகற்றப்பட்ட கழிவு',
    safetyScore: 'பாதுகாப்பு மதிப்பெண்',
    shift: 'பணி நேரம்'
  },
  te: {
    brandName: 'స్మార్ట్‌స్వీప్',
    citizenPortal: 'పౌర పోర్టల్',
    crewPortal: 'పారిశుధ్య సిబ్బంది పోర్టల్',
    adminPortal: 'అడ్మిన్ కమాండ్ పోర్టల్',
    home: 'హోమ్',
    citizenHub: 'సిటిజన్ హబ్',
    crewDashboard: 'సిబ్బంది డాష్‌బోర్డ్',
    commandCenter: 'కమాండ్ సెంటర్',
    reportIssue: 'ఫిర్యాదు నమోదు చేయండి',
    myComplaints: 'నా ఫిర్యాదులు',
    bulkPickup: 'భారీ వ్యర్థాల సేకరణ',
    schedule: 'సమయ పట్టిక',
    publicFeed: 'పబ్లిక్ ఫీడ్',
    assignedTasks: 'కేటాయించిన పనులు',
    bulkDispatches: 'భారీ వాహన పంపకాలు',
    fleetVehicles: 'ఫ్లీట్ & ట్రక్కులు',
    toolsPPE: 'రక్షణ పరికరాలు',
    reportsTrends: 'నివేదికలు & విశ్లేషణ',
    workforce: 'శ్రామిక శక్తి',
    fleetDispatch: 'వాహన డిస్పాచ్',
    signIn: 'లాగిన్ చేయండి',
    signOut: 'లాగ్ అవుట్',
    createAccount: 'ఖాతా సృష్టించండి',
    welcomeBack: 'స్మార్ట్‌స్వీప్‌కి స్వాగతం',
    totalCaseload: 'మొత్తం కేసులు',
    pending: 'పెండింగ్‌లో ఉంది',
    inProgress: 'పురోగతిలో ఉంది',
    resolved: 'పరిష్కరించబడింది',
    cancelled: 'రద్దు చేయబడింది',
    enRoute: 'దారిలో ఉంది',
    slaCompliance: 'SLA సమ్మతి',
    activeDispatches: 'యాక్టివ్ వాహనాలు',
    hazard: 'ప్రమాద స్థాయి',
    location: 'ప్రాంతం',
    ward: 'వార్డు',
    actions: 'చర్యలు',
    switchPortal: 'పోర్టల్ మార్చండి',
    themeMode: 'థీమ్ మోడ్',
    darkForest: 'డార్క్ ఫారెస్ట్',
    crispLight: 'లైట్ మోడ్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    fileWasteReport: 'ఫిర్యాదు చేయండి',
    bookBulkPickup: 'వ్యర్థాల సేకరణ బుక్ చేయండి',
    viewTimetable: 'టైమ్‌టేబుల్ చూడండి',
    viewFeed: 'లైవ్ స్ట్రీమ్ చూడండి',
    todayCollection: 'నేటి వ్యర్థాల సేకరణ సమయం',
    morningSlot: 'ఉదయం సేకరణ',
    eveningSlot: 'సాయంత్రం శుభ్రత',
    attachPhoto: 'ఫోటో జతచేయండి',
    submitReport: 'సమర్పించండి',
    detectGPS: 'GPS గుర్తింపు',
    rateResolution: 'రేటింగ్ ఇవ్వండి',
    applaud: 'అభినందించండి',
    applauded: 'అభినందించారు!',
    discussion: 'చర్చ',
    wasteRemoved: 'తొలగించిన వ్యర్థాలు',
    safetyScore: 'భద్రతా స్కోరు',
    shift: 'డ్యూటీ షిఫ్ట్'
  },
  mr: {
    brandName: 'स्मार्टस्वीप',
    citizenPortal: 'नागरिक पोर्टल',
    crewPortal: 'स्वच्छता कर्मचारी पोर्टल',
    adminPortal: 'प्रशासकीय नियंत्रण पोर्टल',
    home: 'मुख्यपृष्ठ',
    citizenHub: 'नागरिक केंद्र',
    crewDashboard: 'कर्मचारी डॅशबोर्ड',
    commandCenter: 'नियंत्रण कक्ष',
    reportIssue: 'तक्रार नोंदवा',
    myComplaints: 'माझ्या तक्रारी',
    bulkPickup: 'मोठा कचरा उचलणे',
    schedule: 'वेळापत्रक',
    publicFeed: 'सार्वजनिक फीड',
    assignedTasks: 'नियुक्त केलेली कामे',
    bulkDispatches: 'मोठी कचरा वाहने',
    fleetVehicles: 'वाहने व ट्रक्स',
    toolsPPE: 'सुरक्षा उपकरणे',
    reportsTrends: 'अहवाल व विश्लेषण',
    workforce: 'कर्मचारी वर्ग',
    fleetDispatch: 'वाहन पाठवणे',
    signIn: 'साइन इन करा',
    signOut: 'साइन आउट',
    createAccount: 'नवीन खाते तयार करा',
    welcomeBack: 'स्मार्टस्वीप मध्ये आपले स्वागत आहे',
    totalCaseload: 'एकूण प्रकरणे',
    pending: 'प्रलंबित',
    inProgress: 'प्रगतीपथावर',
    resolved: 'निकाली काढले',
    cancelled: 'रद्द केले',
    enRoute: 'मार्गावर',
    slaCompliance: 'SLA अनुपालन',
    activeDispatches: 'सक्रिय वाहने',
    hazard: 'धोका पातळी',
    location: 'स्थान',
    ward: 'प्रभाग / वॉर्ड',
    actions: 'कृती',
    switchPortal: 'पोर्टल बदला',
    themeMode: 'थीम मोड',
    darkForest: 'डार्क फॉरेस्ट',
    crispLight: 'लाईट मोड',
    selectLanguage: 'भाषा निवडा',
    fileWasteReport: 'कचरा तक्रार दाखल करा',
    bookBulkPickup: 'मोठा कचरा पिकअप बुक करा',
    viewTimetable: 'वेळापत्रक पहा',
    viewFeed: 'थेट फीड पहा',
    todayCollection: 'आजची कचरा संकलन वेळ',
    morningSlot: 'सकाळचे संकलन',
    eveningSlot: 'संध्याकाळची स्वच्छता',
    attachPhoto: 'फोटो जोडा',
    submitReport: 'अहवाल सादर करा',
    detectGPS: 'GPS द्वारे शोधा',
    rateResolution: 'रेटिंग द्या',
    applaud: 'कौतुक करा',
    applauded: 'कौतुक केले!',
    discussion: 'चर्चा',
    wasteRemoved: 'कचरा हटवला',
    safetyScore: 'सुरक्षा गुण',
    shift: 'शिफ्ट'
  },
  bn: {
    brandName: 'স্মার্টসুইপ',
    citizenPortal: 'নাগরিক পোর্টাল',
    crewPortal: 'পরিচ্ছন্নতা কর্মী পোর্টাল',
    adminPortal: 'প্রশাসনিক কমান্ড পোর্টাল',
    home: 'হোম',
    citizenHub: 'সিটিজেন হাব',
    crewDashboard: 'কর্মী ড্যাশবোর্ড',
    commandCenter: 'কমান্ড সেন্টার',
    reportIssue: 'অভিযোগ দায়ের করুন',
    myComplaints: 'আমার অভিযোগ',
    bulkPickup: 'ভারী বর্জ্য সংগ্রহ',
    schedule: 'সময়সূচী',
    publicFeed: 'পাবলিক ফিড',
    assignedTasks: 'বরাদ্দ কাজ',
    bulkDispatches: 'বর্জ্য পরিবহন',
    fleetVehicles: 'যানবাহন ও ট্রাক',
    toolsPPE: 'সুরক্ষা সামগ্রী',
    reportsTrends: 'প্রতিবেদন ও বিশ্লেষণ',
    workforce: 'কর্মীবাহিনী',
    fleetDispatch: 'যানবাহন প্রেরণ',
    signIn: 'সাইন ইন',
    signOut: 'সাইন আউট',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    welcomeBack: 'স্মার্টসুইপে স্বাগতম',
    totalCaseload: 'মোট অভিযোগ',
    pending: 'অমীমাংসিত',
    inProgress: 'চলমান',
    resolved: 'সমাধান হয়েছে',
    cancelled: 'বাতিল',
    enRoute: 'পথিমধ্যে',
    slaCompliance: 'SLA সম্মতি',
    activeDispatches: 'সক্রিয় যানবাহন',
    hazard: 'বিপদ মাত্রা',
    location: 'অবস্থান',
    ward: 'ওয়ার্ড',
    actions: 'পদক্ষেপ',
    switchPortal: 'পোর্টাল পরিবর্তন',
    themeMode: 'থিম মোড',
    darkForest: 'ডার্ক মোড',
    crispLight: 'লাইট মোড',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    fileWasteReport: 'বর্জ্য অভিযোগ দায়ের করুন',
    bookBulkPickup: 'ভারী বর্জ্য বুক করুন',
    viewTimetable: 'সময়সূচী দেখুন',
    viewFeed: 'লাইভ দেখুন',
    todayCollection: 'আজকের বর্জ্য সংগ্রহের সময়',
    morningSlot: 'সকালের সংগ্রহ',
    eveningSlot: 'সন্ধ্যার পরিচ্ছন্নতা',
    attachPhoto: 'ছবি যুক্ত করুন',
    submitReport: 'জমা দিন',
    detectGPS: 'GPS সনাক্তকরণ',
    rateResolution: 'রেটিং দিন',
    applaud: 'প্রশংসা করুন',
    applauded: 'প্রশংসিত!',
    discussion: 'আলোচনা',
    wasteRemoved: 'অপসারিত বর্জ্য',
    safetyScore: 'সুরক্ষা স্কোর',
    shift: 'শিফট'
  },
  gu: {
    brandName: 'સ્માર્ટસ્વીપ',
    citizenPortal: 'નાગરિક પોર્ટલ',
    crewPortal: 'સફાઈ કર્મચારી પોર્ટલ',
    adminPortal: 'વહીવટી કમાન્ડ પોર્ટલ',
    home: 'હોમ',
    citizenHub: 'સિટિઝન હબ',
    crewDashboard: 'કર્મચારી ડેશબોર્ડ',
    commandCenter: 'કમાન્ડ સેન્ટર',
    reportIssue: 'ફરિયાદ નોંધાવો',
    myComplaints: 'મારી ફરિયાદો',
    bulkPickup: 'મોટો કચરો ઉપાડવો',
    schedule: 'સમયપત્રક',
    publicFeed: 'જાહેર ફીડ',
    assignedTasks: 'સોંપેલ કાર્યો',
    bulkDispatches: 'કચરા વાહનો',
    fleetVehicles: 'વાહનો અને ટ્રક',
    toolsPPE: 'સુરક્ષા સાધનો',
    reportsTrends: 'અહેવાલો અને આંકડા',
    workforce: 'કર્મચારીઓ',
    fleetDispatch: 'વાહન રવાનગી',
    signIn: 'સાઇન ઇન',
    signOut: 'સાઇન આઉટ',
    createAccount: 'ખાતું બનાવો',
    welcomeBack: 'સ્માર્ટસ્વીપમાં આપનું સ્વાગત છે',
    totalCaseload: 'કુલ કેસો',
    pending: 'બાકી',
    inProgress: 'પ્રગતિમાં',
    resolved: 'ઉકેલાયેલ',
    cancelled: 'રદ કરેલ',
    enRoute: 'રસ્તામાં',
    slaCompliance: 'SLA પાલન',
    activeDispatches: 'સક્રિય વાહનો',
    hazard: 'જોખમ સ્તર',
    location: 'સ્થળ',
    ward: 'વોર્ડ',
    actions: 'ક્રિયાઓ',
    switchPortal: 'પોર્ટલ બદલો',
    themeMode: 'થીમ મોડ',
    darkForest: 'ડાર્ક ફોરેસ્ટ',
    crispLight: 'લાઇટ મોડ',
    selectLanguage: 'ભાષા પસંદ કરો',
    fileWasteReport: 'કચરાની ફરિયાદ નોંધાવો',
    bookBulkPickup: 'મોટો કચરો બુક કરો',
    viewTimetable: 'સમયપત્રક જુઓ',
    viewFeed: 'લાઇવ જુઓ',
    todayCollection: 'આજનો કચરો એકત્ર કરવાનો સમય',
    morningSlot: 'સવારનું એકત્રીકરણ',
    eveningSlot: 'સાંજની સફાઈ',
    attachPhoto: 'ફોટો જોડો',
    submitReport: 'સબમિટ કરો',
    detectGPS: 'GPS શોધો',
    rateResolution: 'રેટિંગ આપો',
    applaud: 'પ્રશંસા કરો',
    applauded: 'પ્રશંસા કરી!',
    discussion: 'ચર્ચા',
    wasteRemoved: 'હટાવેલ કચરો',
    safetyScore: 'સુરક્ષા સ્કોર',
    shift: 'શિફ્ટ'
  },
  ml: {
    brandName: 'സ്മാർട്ട്‌സ്വീപ്പ്',
    citizenPortal: 'പൗര പോർട്ടൽ',
    crewPortal: 'ശുചീകരണ തൊഴിലാളി പോർട്ടൽ',
    adminPortal: 'അഡ്മിൻ കമാൻഡ് പോർട്ടൽ',
    home: 'ഹോം',
    citizenHub: 'സിറ്റിസൺ ഹബ്ബ്',
    crewDashboard: 'തൊഴിലാളി ഡാഷ്‌ബോർഡ്',
    commandCenter: 'കമാൻഡ് സെന്റർ',
    reportIssue: 'പരാതി നൽകുക',
    myComplaints: 'എന്റെ പരാതികൾ',
    bulkPickup: 'വൻകിട മാലിന്യ ശേഖരണം',
    schedule: 'സമയക്രമം',
    publicFeed: 'പബ്ലിക് ഫീഡ്',
    assignedTasks: 'നിയുക്ത ജോലികൾ',
    bulkDispatches: 'വാഹന വിന്യാസം',
    fleetVehicles: 'വാഹനങ്ങൾ',
    toolsPPE: 'സുരക്ഷാ ഉപകരണങ്ങൾ',
    reportsTrends: 'റിപ്പോർട്ടുകൾ',
    workforce: 'തൊഴിലാളികൾ',
    fleetDispatch: 'വാഹന അയയ്ക്കൽ',
    signIn: 'സൈൻ ഇൻ',
    signOut: 'സൈൻ ഔട്ട്',
    createAccount: 'അക്കൗണ്ട് നിർമ്മിക്കുക',
    welcomeBack: 'സ്മാർട്ട്‌സ്വീപ്പിലേക്ക് സ്വാഗതം',
    totalCaseload: 'ആകെ കേസുകൾ',
    pending: 'തീർപ്പാക്കാത്തവ',
    inProgress: 'പുരോഗമിക്കുന്നു',
    resolved: 'പരിഹരിച്ചു',
    cancelled: 'റദ്ദാക്കി',
    enRoute: 'വഴിയിലാണ്',
    slaCompliance: 'SLA പാലനം',
    activeDispatches: 'വാഹനങ്ങൾ',
    hazard: 'അപകട സാധ്യത',
    location: 'സ്ഥലം',
    ward: 'വാർഡ്',
    actions: 'നടപടികൾ',
    switchPortal: 'പോർട്ടൽ മാറ്റുക',
    themeMode: 'തീം മോഡ്',
    darkForest: 'ഡാർക്ക് മോഡ്',
    crispLight: 'ലൈറ്റ് മോഡ്',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    fileWasteReport: 'പരാതി സമർപ്പിക്കുക',
    bookBulkPickup: 'മാലിന്യ ശേഖരണം ബുക്ക് ചെയ്യുക',
    viewTimetable: 'സമയക്രമം കാണുക',
    viewFeed: 'ലൈവ് കാണുക',
    todayCollection: 'ഇന്നത്തെ മാലിന്യ ശേഖരണ സമയം',
    morningSlot: 'രാവിലെയുള്ള ശേഖരണം',
    eveningSlot: 'വൈകുന്നേര ശുചീകരണം',
    attachPhoto: 'ഫോട്ടോ ചേർക്കുക',
    submitReport: 'സമർപ്പിക്കുക',
    detectGPS: 'GPS കണ്ടെത്തുക',
    rateResolution: 'റേറ്റിംഗ് നൽകുക',
    applaud: 'അഭിനന്ദിക്കുക',
    applauded: 'അഭിനന്ദിച്ചു!',
    discussion: 'ചർച്ച',
    wasteRemoved: 'നീക്കം ചെയ്ത മാലിന്യം',
    safetyScore: 'സുരക്ഷാ സ്കോർ',
    shift: 'ഷിഫ്റ്റ്'
  },
  pa: {
    brandName: 'ਸਮਾਰਟਸਵੀਪ',
    citizenPortal: 'ਨਾਗਰਿਕ ਪੋਰਟਲ',
    crewPortal: 'ਸਫ਼ਾਈ ਕਰਮਚਾਰੀ ਪੋਰਟਲ',
    adminPortal: 'ਪ੍ਰਬੰਧਕੀ ਕਮਾਂਡ ਪੋਰਟਲ',
    home: 'ਹੋਮ',
    citizenHub: 'ਨਾਗਰਿਕ ਹੱਬ',
    crewDashboard: 'ਕਰਮਚਾਰੀ ਡੈਸ਼ਬੋਰਡ',
    commandCenter: 'ਕਮਾਂਡ ਸੈਂਟਰ',
    reportIssue: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    myComplaints: 'ਮੇਰੀਆਂ ਸ਼ਿਕਾਇਤਾਂ',
    bulkPickup: 'ਵੱਡਾ ਕੂੜਾ ਚੁੱਕਣਾ',
    schedule: 'ਸਮਾਂ ਸਾਰਣੀ',
    publicFeed: 'ਜਨਤਕ ਫੀਡ',
    assignedTasks: 'ਸੌਂਪੇ ਗਏ ਕੰਮ',
    bulkDispatches: 'ਕੂੜਾ ਵਾਹਨ',
    fleetVehicles: 'ਵਾਹਨ ਅਤੇ ਟਰੱਕ',
    toolsPPE: 'ਸੁਰੱਖਿਆ ਉਪਕਰਣ',
    reportsTrends: 'ਰਿਪੋਰਟਾਂ ਅਤੇ ਅੰਕੜੇ',
    workforce: 'ਕਰਮਚਾਰੀ',
    fleetDispatch: 'ਵਾਹਨ ਭੇਜਣਾ',
    signIn: 'ਸਾਈਨ ਇਨ',
    signOut: 'ਸਾਈਨ ਆਊਟ',
    createAccount: 'ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ',
    welcomeBack: 'ਸਮਾਰਟਸਵੀਪ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
    totalCaseload: 'ਕੁੱਲ ਮਾਮਲੇ',
    pending: 'ਬਕਾਇਆ',
    inProgress: 'ਚੱਲ ਰਿਹਾ ਹੈ',
    resolved: 'ਹੱਲ ਹੋ ਗਿਆ',
    cancelled: 'ਰੱਦ ਕੀਤਾ ਗਿਆ',
    enRoute: 'ਰਸਤੇ ਵਿੱਚ',
    slaCompliance: 'SLA ਪਾਲਣਾ',
    activeDispatches: 'ਸਰਗਰਮ ਵਾਹਨ',
    hazard: 'ਖ਼ਤਰਾ ਪੱਧਰ',
    location: 'ਸਥਾਨ',
    ward: 'ਵਾਰਡ',
    actions: 'ਕਾਰਵਾਈਆਂ',
    switchPortal: 'ਪੋਰਟਲ ਬਦਲੋ',
    themeMode: 'ਥੀਮ ਮੋਡ',
    darkForest: 'ਡਾਰਕ ਫਾਰੈਸਟ',
    crispLight: 'ਲਾਈਟ ਮੋਡ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    fileWasteReport: 'ਕੂੜੇ ਦੀ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    bookBulkPickup: 'ਵੱਡਾ ਕੂੜਾ ਚੁੱਕਣਾ ਬੁੱਕ ਕਰੋ',
    viewTimetable: 'ਸਮਾਂ ਸਾਰਣੀ ਦੇਖੋ',
    viewFeed: 'ਲਾਈਵ ਦੇਖੋ',
    todayCollection: 'ਅੱਜ ਦਾ ਕੂੜਾ ਚੁੱਕਣ ਦਾ ਸਮਾਂ',
    morningSlot: 'ਸਵੇਰ ਦਾ ਸਮਾਂ',
    eveningSlot: 'ਸ਼ਾਮ ਦੀ ਸਫ਼ਾਈ',
    attachPhoto: 'ਫੋਟੋ ਨੱਥੀ ਕਰੋ',
    submitReport: 'ਜਮ੍ਹਾਂ ਕਰੋ',
    detectGPS: 'GPS ਰਾਹੀਂ ਲੱਭੋ',
    rateResolution: 'ਰੇਟਿੰਗ ਦਿਓ',
    applaud: 'ਸ਼ਲਾਘਾ ਕਰੋ',
    applauded: 'ਸ਼ਲਾਘਾ ਕੀਤੀ ਗਈ!',
    discussion: 'ਚਰਚਾ',
    wasteRemoved: 'ਹਟਾਇਆ ਗਿਆ ਕੂੜਾ',
    safetyScore: 'ਸੁਰੱਖਿਆ ਸਕੋਰ',
    shift: 'ਡਿਊਟੀ ਸ਼ਿਫਟ'
  },
  or: {
    brandName: 'ସ୍ମାର୍ଟସ୍ୱୀପ୍',
    citizenPortal: 'ନାଗରିକ ପୋର୍ଟାଲ',
    crewPortal: 'ସଫେଇ କର୍ମଚାରୀ ପୋର୍ଟାଲ',
    adminPortal: 'ପ୍ରଶାସନିକ କମାଣ୍ଡ ପୋର୍ଟାଲ',
    home: 'ମୂଳପୃଷ୍ଠା',
    citizenHub: 'ନାଗରିକ ହବ୍',
    crewDashboard: 'କର୍ମଚାରୀ ଡ୍ୟାସବୋର୍ଡ',
    commandCenter: 'କମାଣ୍ଡ ସେଣ୍ଟର',
    reportIssue: 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
    myComplaints: 'ମୋର ଅଭିଯୋଗ',
    bulkPickup: 'ଭାରୀ ଆବର୍ଜନା ସଂଗ୍ରହ',
    schedule: 'ସମୟସାରଣୀ',
    publicFeed: 'ସାର୍ବଜନୀନ ଫିଡ୍',
    assignedTasks: 'ନ୍ୟସ୍ତ କାର୍ଯ୍ୟ',
    bulkDispatches: 'ଆବର୍ଜନା ଗାଡ଼ି',
    fleetVehicles: 'ଗାଡ଼ି ଓ ଟ୍ରକ୍',
    toolsPPE: 'ସୁରକ୍ଷା ଉପକରଣ',
    reportsTrends: 'ରିପୋର୍ଟ ଓ ତଥ୍ୟ',
    workforce: 'କର୍ମଚାରୀ ବର୍ଗ',
    fleetDispatch: 'ଗାଡ଼ି ପ୍ରେରଣ',
    signIn: 'ଲଗ୍ ଇନ୍',
    signOut: 'ଲଗ୍ ଆଉଟ୍',
    createAccount: 'ଖାତା ଖୋଲନ୍ତୁ',
    welcomeBack: 'ସ୍ମାର୍ଟସ୍ୱୀପ୍ କୁ ସ୍ୱାଗତ',
    totalCaseload: 'ମୋଟ ମାମଲା',
    pending: 'ବାକି ଅଛି',
    inProgress: 'ଚାଲିଛି',
    resolved: 'ସମାଧାନ ହୋଇଛି',
    cancelled: 'ବାତିଲ୍',
    enRoute: 'ବାଟରେ ଅଛି',
    slaCompliance: 'SLA ନିୟମ ପାଳନ',
    activeDispatches: 'ସକ୍ରିୟ ଗାଡ଼ି',
    hazard: 'ବିପଦ ସ୍ତର',
    location: 'ସ୍ଥାନ',
    ward: 'ୱାର୍ଡ',
    actions: 'କାର୍ଯ୍ୟାନୁଷ୍ଠାନ',
    switchPortal: 'ପୋର୍ଟାଲ୍ ବଦଳାନ୍ତୁ',
    themeMode: 'ଥିମ୍ ମୋଡ୍',
    darkForest: 'ଡାର୍କ ମୋଡ୍',
    crispLight: 'ଲାଇଟ୍ ମୋଡ୍',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    fileWasteReport: 'ଅଭିଯୋଗ କରନ୍ତୁ',
    bookBulkPickup: 'ଭାରୀ କଚରା ବୁକ୍ କରନ୍ତୁ',
    viewTimetable: 'ସମୟସାରଣୀ ଦେଖନ୍ତୁ',
    viewFeed: 'ଲାଇଭ୍ ଦେଖନ୍ତୁ',
    todayCollection: 'ଆଜିର ଆବର୍ଜନା ସଂଗ୍ରହ ସମୟ',
    morningSlot: 'ସକାଳ ସଂଗ୍ରହ',
    eveningSlot: 'ସନ୍ଧ୍ୟା ସଫେଇ',
    attachPhoto: 'ଫଟୋ ଯୋଡ଼ନ୍ତୁ',
    submitReport: 'ଦାଖଲ କରନ୍ତୁ',
    detectGPS: 'GPS ଠଉରାନ୍ତୁ',
    rateResolution: 'ରେଟିଂ ଦିଅନ୍ତୁ',
    applaud: 'ପ୍ରଶଂସା କରନ୍ତୁ',
    applauded: 'ପ୍ରଶଂସିତ!',
    discussion: 'ଆଲୋଚନା',
    wasteRemoved: 'ହଟାଯାଇଥିବା ଆବର୍ଜନା',
    safetyScore: 'ସୁରକ୍ଷା ସ୍କୋର',
    shift: 'ଡ୍ୟୁଟି ସିଫ୍ଟ'
  },
  ur: {
    brandName: 'اسمارٹ سویپ',
    citizenPortal: 'شہری پورٹل',
    crewPortal: 'صفائی عملہ پورٹل',
    adminPortal: 'ایڈمن کمانڈ پورٹل',
    home: 'ہوم',
    citizenHub: 'سٹی زن ہب',
    crewDashboard: 'عملہ ڈیش بورڈ',
    commandCenter: 'کمانڈ سنٹر',
    reportIssue: 'شکایت درج کریں',
    myComplaints: 'میری شکایات',
    bulkPickup: 'بھاری کچرا اٹھانا',
    schedule: 'ٹائم ٹیبل',
    publicFeed: 'عوامی فیڈ',
    assignedTasks: 'تفویض کردہ کام',
    bulkDispatches: 'کچرا گاڑیاں',
    fleetVehicles: 'گاڑیاں اور ٹرک',
    toolsPPE: 'حفاظتی سامان',
    reportsTrends: 'رپورٹس اور تجزیات',
    workforce: 'عملہ',
    fleetDispatch: 'گاڑی روانگی',
    signIn: 'سائن ان',
    signOut: 'سائن آؤٹ',
    createAccount: 'اکاؤنٹ بنائیں',
    welcomeBack: 'اسمارٹ سویپ میں خوش آمدید',
    totalCaseload: 'کل مقدمات',
    pending: 'زیر التواء',
    inProgress: 'جاری ہے',
    resolved: 'حل ہو گیا',
    cancelled: 'منسوخ',
    enRoute: 'راستے میں',
    slaCompliance: 'SLA تعمیل',
    activeDispatches: 'فعال گاڑیاں',
    hazard: 'خطرے کی سطح',
    location: 'مقام / پتہ',
    ward: 'وارڈ',
    actions: 'اقدامات',
    switchPortal: 'پورٹل تبدیل کریں',
    themeMode: 'تھیم موڈ',
    darkForest: 'ڈارک فارسٹ',
    crispLight: 'لائٹ موڈ',
    selectLanguage: 'زبان منتخب کریں',
    fileWasteReport: 'کچرے کی شکایت درج کریں',
    bookBulkPickup: 'بھاری کچرا بک کریں',
    viewTimetable: 'ٹائم ٹیبل دیکھیں',
    viewFeed: 'لائیو دیکھیں',
    todayCollection: 'آج کا کچرا جمع کرنے کا وقت',
    morningSlot: 'صبح کا وقت',
    eveningSlot: 'شام کی صفائی',
    attachPhoto: 'تصویر منسلک کریں',
    submitReport: 'رپورٹ جمع کریں',
    detectGPS: 'GPS سے پتہ لگائیں',
    rateResolution: 'درجہ بندی کریں',
    applaud: 'تعریف کریں',
    applauded: 'تعریف کی گئی!',
    discussion: 'بحث',
    wasteRemoved: 'ہٹایا گیا کچرا',
    safetyScore: 'حفاظتی اسکور',
    shift: 'ڈیوٹی شفٹ'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('smartsweep-lang');
    return saved || 'en'; // Default language is English
  });

  useEffect(() => {
    localStorage.setItem('smartsweep-lang', language);
  }, [language]);

  const t = (key) => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
